name: Classic Strong Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. جلب الكود
      - uses: actions/checkout@v3
      
      # 2. تجهيز الجافا (مهم للأندرويد)
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          
      # 3. تجهيز Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      # 4. تحميل المكتبات
      - run: flutter pub get
      
      # 5. البناء (بدون ضغط الأيقونات لتجنب المشاكل)
      - run: flutter build apk --release --no-tree-shake-icons
      
      # 6. الرفع لك
      - uses: actions/upload-artifact@v3
        with:
          name: tijarati-classic
          path: build/app/outputs/flutter-apk/app-release.apk
