name: Classic Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # استخدام جافا 17 (الأكثر استقراراً حالياً)
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - run: flutter pub get
      
      # أمر البناء البسيط (بدون توقيعات معقدة)
      - run: flutter build apk --release --no-tree-shake-icons
      
      # الرفع
      - uses: actions/upload-artifact@v3
        with:
          name: tijarati-app
          path: build/app/outputs/flutter-apk/app-release.apk
